### ISSUE TITLE
Rewrite to use `ember-elsewhere`

### ISSUE THREAD

**Issue by srowhani** [ciena-frost/ember-frost-navigation#76]
It looks like liquid-fire has dropped support for its `modal`. This issue, found here https://github.com/ember-animation/liquid-fire/issues/484 blocks moving into `ember: ^2.8.0`

The best option would be to reimplement the modal.

- [x] Update liquid fire dependency to `~0.25.0`
- [x] Integrate ember elsewhere

**Comment by rox163** [comment]
Sweet. Going to need this for engines with nav. I upgraded our test engine to Ember 2.8 recently and nav doesn't work anymore because of this 0.25.x liquid modal issue.
